param(
    [string]$BinPath,
    [string]$OutDir
)

$outPath = Join-Path $OutDir "raw_data.h"
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

$bytes = [IO.File]::ReadAllBytes($BinPath)
$timestamp = (Get-Date -Format "yyyy-MM-dd HH:mm:ss") + " Local"
$hashBytes = [System.Security.Cryptography.SHA256]::Create().ComputeHash($bytes)
$fileHash = ($hashBytes[0..15] | ForEach-Object {$_.ToString("x2")}) -join ""

$sb = New-Object System.Text.StringBuilder
$sb.AppendLine("/* ===========================================================================") | Out-Null
$sb.AppendLine(" *  AUTO-GENERATED FILE - DO NOT EDIT unless you know what you're doing!!") | Out-Null
$sb.AppendLine(" *  ---------------------------------------------------------------------------") | Out-Null
$genBy = " *  Generated by : build.bat"
$sb.AppendLine($genBy.PadRight(78)) | Out-Null
$tsLine = " *  Timestamp    : " + $timestamp
$sb.AppendLine($tsLine.PadRight(78)) | Out-Null
$fileLine = " *  File         : raw_data.h"
$sb.AppendLine($fileLine.PadRight(78)) | Out-Null
$hashLine = " *  Source Hash:  " + $fileHash
$sb.AppendLine($hashLine.PadRight(78)) | Out-Null
$sb.AppendLine(" *  This file is produced automatically during the build process.") | Out-Null
$sb.AppendLine(" *  Manual edits will be overwritten on the next regeneration.") | Out-Null
$sb.AppendLine(" * ===========================================================================") | Out-Null
$sb.AppendLine(" */") | Out-Null
$sb.AppendLine("#pragma once") | Out-Null
$sb.Append("const unsigned char raw_data[] = {") | Out-Null
$hex = $bytes | ForEach-Object { "0x{0:X2}" -f $_ }
$sb.Append(($hex -join ",")) | Out-Null
$sb.AppendLine("};") | Out-Null
$sb.AppendLine("const unsigned int raw_data_len = " + $bytes.Length + ";") | Out-Null

[IO.File]::WriteAllText($outPath, $sb.ToString())

$fileSize = $bytes.Length
if ($fileSize -ge 1024) {
    $fileSizeKB = [math]::Truncate($fileSize / 1024)
    $fileSizeRem = $fileSize % 1024
    $fileSizeDec = [math]::Truncate($fileSizeRem * 100 / 1024)
    if ($fileSizeDec -lt 10) {
        Write-Host "   [OK] Generated raw_data.h ($($fileSizeKB).0$($fileSizeDec) KB ($fileSize bytes))"
    } else {
        Write-Host "   [OK] Generated raw_data.h ($($fileSizeKB).$($fileSizeDec) KB ($fileSize bytes))"
    }
} else {
    Write-Host "   [OK] Generated raw_data.h ($fileSize bytes)"
}

